title: "F.U.C.K."
subtitle: "Journal of Formulal Unnecessary Commentary & Knowledge"
description: "A peer-reviewed (by no one) academic journal dedicated to the rigorous study of Formula 1 nonsense."
tagline: "Advancing the frontier of motorsport bullshit since 2026"

github_username: ashley0-926
repo_name: fuck-journal

issn: "3000-FUCK"
abbreviation: "F.U.C.K."

baseurl: ""
url: ""

markdown: kramdown
theme: null
plugins: []

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - api
